<?php

/**
 * This module exposes the Silverpop Engage XML API to other Drupal modules.
 * It provides a number of popular API methods via the silverpopAPI class.
 * In order to utilize it with your own Silverpop account, you'll need to
 * configure a few settings at admin/settings/silverpop.
 * It also provides a config-only option to use Silverpop for all system emails.
 * See silverpopAPI.inc for more info on the API methods supported.
 * See silverpopXML.inc for more info on the core data connection to Silverpop.
 */

module_load_include('inc', 'silverpop', 'silverpopAPI');
module_load_include('inc', 'silverpop', 'simple_html_dom');

/**
 * Implementation of hook_menu().
 */
function silverpop_menu() {

  $items = array();
  $items['admin/config/silverpop'] = array(
    'title' => 'Silverpop',
    'description' => t('Silverpop API Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('silverpop_admin_settings_form'),
    'access arguments' => array('administer silverpop'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/silverpop/settings'] = array(
    'title' => 'Silverpop Settings',
    'description' => t('Silverpop API Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('silverpop_admin_settings_form'),
    'access arguments' => array('administer silverpop'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

/**
 * Implementation of hook_perm().
 */
function silverpop_perm() {
  return array('administer silverpop');
}

/**
 * Silverpop account configuration.
 * @return mixed
 */
function silverpop_admin_settings_form() {

  $form['connection'] = array(
    '#type' => 'fieldset',
    '#title' => t('Account/Connection'),
    '#description' => t('Fundamental details about your Silverpop account.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['connection']['silverpop_endpoint'] = array(
    '#type' => 'textfield',
    '#title' => t('Endpoint'),
    '#description' => t('The URL of the Silverpop API endpoint to use. This '
      . 'varies according to the Silverpop "pod" associated with your '
      . 'account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#default_value' => variable_get('silverpop_endpoint', NULL),
  );

  $form['connection']['silverpop_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#description' => t('Your Silverpop username.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_userid', NULL),
  );

  $form['connection']['silverpop_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('Your Silverpop password.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_password', NULL),
  );

  $form['connection']['silverpop_oauth_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('OAuth Client ID'),
    '#description' => t('The client ID generated when you added this '
      . 'module as an application in your Silverpop org settings.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_oauth_client_id', NULL),
  );

  $form['connection']['silverpop_oauth_client_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('OAuth Client Secret'),
    '#description' => t('The client secret generated when you added this '
    . 'module as an application in your Silverpop org settings.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_oauth_client_secret', NULL),
  );

  $form['connection']['silverpop_oauth_refresh_token'] = array(
    '#type' => 'textfield',
    '#title' => t('OAuth Refresh Token'),
    '#description' => t('The "User Account Refresh Token" that Silverpop '
      . 'provided when you granted a Silverpop user access to this '
      . 'module\'s application in your Silverpop org settings. This token '
      . 'should have been emailed to the notification email address of the '
      . 'org admin who granted the module access.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_oauth_refresh_token', NULL),
  );

  $form['ftp'] = array(
    '#type' => 'fieldset',
    '#title' => t('FTP Connection'),
    '#description' => t('Access info for your Engage FTP repository'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['ftp']['silverpop_ftp_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host'),
    '#description' => t('e.g. transfer1.silverpop.com'),
    '#size' => 40,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#default_value' => variable_get('silverpop_ftp_host', NULL),
  );

  $form['ftp']['silverpop_ftp_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#description' => t('Your FTP username.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_ftp_username', NULL),
  );

  $form['ftp']['silverpop_ftp_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('Your FTP password.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_ftp_password', NULL),
  );

  $form['account_details'] = array(
    '#type' => 'fieldset',
    '#title' => t('Account Configuration Details'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['account_details']['silverpop_default_listid'] = array(
    '#type' => 'textfield',
    '#title' => t('Default List/Database ID'),
    '#description' => t('The ID of the Silverpop database/list to use when '
      . 'none is explicitly specified.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_default_listid', NULL),
  );

  $form['account_details']['silverpop_default_templateid'] = array(
    '#type' => 'textfield',
    '#title' => t('Default Template ID'),
    '#description' => t('The ID of the Silverpop mailing template to use when '
      . 'none is explicitly specified.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_default_templateid', NULL),
  );

  $form['account_details']['silverpop_db_is_uid_keyed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Database is Keyed by UID'),
    '#description' => t('Select this option if your Silverpop database uses '
      . 'a field based on the drupal user ID as its primary identifier, rather '
      . 'than using the default "Email" field. Structuring your database in '
      . 'this way can improve data integrity and streamline user actions such '
      . 'as changing email addresses.'),
    '#default_value' => variable_get('silverpop_db_is_uid_keyed', NULL),
  );

  $form['account_details']['silverpop_primary_key_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Unique Identifier Field Name'),
    '#description' => t('The name of the field that is the primary unique '
      . 'identifier in your Silverpop database (defaults to "DRUPAL_USER_ID"). '
      . 'This is only required for databases that do not use "Email" as the '
      . 'primary key.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_primary_key_name', 'DRUPAL_USER_ID'),
  );

  $form['analytics'] = array(
    '#type' => 'fieldset',
    '#title' => t('Analytics'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['analytics']['silverpop_domains_to_exclude_from_tracking'] = array(
    '#type' => 'textfield',
    '#title' => t('Domains/Patterns to Exclude'),
    '#description' => t('You can optionally specify that you do not want '
      . 'Silverpop to modify links that match certain patterns. You can enter '
      . 'multiple strings here, separated by commas. Any link that contains '
      . 'any of these strings will neither have Silverpop tracking applied to '
      . 'it nor be appended with the "append string" given below.'),
    '#size' => 128,
    '#maxlength' => 512,
    '#default_value' => variable_get('silverpop_domains_to_exclude_from_tracking', NULL),
  );

  $form['analytics']['silverpop_dll_server'] = array(
    '#type' => 'textfield',
    '#title' => t('DLL Server'),
    '#description' => t('The URL of the server to use for Engage Dynamic Link '
      . 'Leader (DLL) URL encoding. The server varies according to the '
      . 'Silverpop "pod" associated with your account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('silverpop_dll_server', NULL),
  );

  $form['analytics']['silverpop_url_append_string'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Append String'),
    '#description' => t('A string to append to all links within the content of '
      . 'a mailing. This applies to links that are sent to Silverpop via the '
      . 'API, and not to links that reside in templates composed in Silverpop. '
      . 'This can be used, for example, to add Google Analytics tracking '
      . 'parameters to links.'),
    '#size' => 128,
    '#maxlength' => 512,
    '#default_value' => variable_get('silverpop_url_append_string', NULL),
  );

  $form['analytics']['silverpop_url_append_string_domains'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Append String Domain(s)'),
    '#description' => t('You can optionally specify that the URL append string '
      . '(listed above) should only be appended to links that point to a given '
      . 'domain. You can also specify multiple domains by separating each with '
      . 'a comma.'),
    '#size' => 128,
    '#maxlength' => 512,
    '#default_value' => variable_get('silverpop_url_append_string_domains', NULL),
  );

  $form['analytics']['silverpop_transactional_track_links'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track Links in Transactional Emails'),
    '#description' => t('Enable link tracking (as defined above) for links in '
      . 'any transactional emails sent via Silverpop.'),
    '#default_value' => variable_get('silverpop_transactional_track_links', TRUE),
  );

  $form['reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Reports'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['reports']['transactional_dashboard_link'] = array(
    '#value' => '<p>'
      . t('You can view statistics about transactional mailings in '
      . 'interactive table format using the ')
      . l('transactional reporting dashboard', 'admin/reports/silverpop-transactional')
      . '</p>',
  );

  // Render this form in the standard system settings format...
  $form_output = system_settings_form($form);

  return $form_output;
}

/**
 * Helper function to log events (e.g. errors encountered when attempting to
 *  send mailings with Silverpop)
 *
 * @param $event_type
 * @param $event_name
 * @param $data
 * @param null $timestamp
 */
function silverpop_log($event_type, $event_name, $recipient_email = NULL, $recipient_uid = NULL, $data = array(), $timestamp = NULL) {
  if (empty($timestamp)) {
    $timestamp = time();
  }

  $field_data = array(
    'event_type' => $event_type,
    'event_name' => $event_name,
    'recipient_email' => $recipient_email,
    'recipient_uid' => $recipient_uid,
    'timestamp' => $timestamp,
    'data' => serialize($data),
  );
  // @todo: confirm D7 operation/syntax.
  db_insert('silverpop_log')
    ->fields($field_data)
    ->execute();
}