<?php

/**
 * Implements hook_install().
 */
function silverpop_transactional_install() {
}

/**
 * Implements hook_uninstall().
 */
function silverpop_transactional_uninstall() {
  variable_del('silverpop_replace_standard_mail');
  variable_del('silverpop_transactional_default_template_id');
  variable_del('silverpop_export_unexported_only');
  variable_del('silverpop_transactional_field_name');
  variable_del('silverpop_transactional_field_count');
  variable_del('silverpop_use_standard_mail_as_fallback');
  variable_del('silverpop_transactional_failure_threshold');
  variable_del('silverpop_transactional_failure_threshold_timespan');
  variable_del('silverpop_transactional_recipients_not_in_silverpop');
}

/**
 * Implements hook_schema().
 */
function silverpop_transactional_schema() {
  $schema['silverpop_transactional_mapping'] = array(
    'fields' => array(
      'drupal_mail_key' => array('type' => 'varchar', 'length' => 255, 'not null' => TRUE),
      'sp_mailing_id' => array('type' => 'int', 'not null' => FALSE),
    ),
    'primary key' => array('drupal_mail_key', 'sp_mailing_id'),
  );

  return $schema;
}